; Script generated by Inno Setup Script Wizard
; SEE THE DOCUMENTATION FOR DETAILS: http://www.jrsoftware.org/ishelp/

[Setup]
AppName=PTEEAIAgent
AppVersion=1.0
AppPublisher=Your Company
; AppPublisherURL=http://example.com
; AppSupportURL=http://example.com
; AppUpdatesURL=http://example.com
DefaultDirName={autopf}\PTEEAIAgent
DefaultGroupName=PTEEAIAgent
OutputBaseFilename=PTEEAIAgent Setup
Compression=lzma
SolidCompression=yes
; SetupIconFile=icon.ico ; Thay bằng file icon nếu có
PrivilegesRequired=admin
OutputDir=Output
UninstallDisplayName=PTEEAIAgent
UninstallDisplayIcon={app}\PTEEAIAgent.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "uninstallapp"; Description: "Uninstall the application"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "F:\Python\qtweb-test-app\dist\PTEEAIAgent.exe"; DestDir: "{app}"; Flags: ignoreversion
; Nếu có file phụ như .env hoặc cacert.pem, thêm vào đây
; Source: "dist\.env"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Shortcut trong Start Menu để chạy ứng dụng
Name: "{group}\PTEEAIAgent"; Filename: "{app}\PTEEAIAgent.exe"
; Shortcut trong Start Menu để gỡ cài đặt
Name: "{group}\Uninstall PTEEAIAgent"; Filename: "{uninstallexe}"
; Shortcut trên Desktop (nếu chọn task)
Name: "{autodesktop}\PTEEAIAgent"; Filename: "{app}\PTEEAIAgent.exe"; Tasks: desktopicon

[Registry]
; Đăng ký Custom URL Protocol: PTEEAIAgent://
Root: HKCR; Subkey: "PTEEAIAgent"; ValueType: string; ValueName: ""; ValueData: "URL:PTEEAIAgent Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell\open"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PTEEAIAgent\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\PTEEAIAgent.exe"" ""%1"""; Flags: uninsdeletekey

[Run]
Filename: "{app}\PTEEAIAgent.exe"; Description: "{cm:LaunchProgram,PTEEAIAgent}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
